package br.com.ofm.gnre.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-06T10:12:14.081-02:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "GnreConfigUF", 
                  wsdlLocation = "file:/C:/Users/PC1/IdeaProjects/gnre-teste/src/main/java/br/com/tropicalia/services/GnreConfigUF.wsdl",
                  targetNamespace = "http://www.gnre.pe.gov.br/webservice/GnreConfigUF") 
public class GnreConfigUF extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.gnre.pe.gov.br/webservice/GnreConfigUF", "GnreConfigUF");
    public final static QName GnreConfigUF = new QName("http://www.gnre.pe.gov.br/webservice/GnreConfigUF", "GnreConfigUF");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/PC1/IdeaProjects/gnre-teste/src/main/java/br/com/tropicalia/services/GnreConfigUF.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GnreConfigUF.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/PC1/IdeaProjects/gnre-teste/src/main/java/br/com/tropicalia/services/GnreConfigUF.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GnreConfigUF(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GnreConfigUF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GnreConfigUF() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GnreConfigUF(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GnreConfigUF(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GnreConfigUF(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GnreConfigUFSoap
     */
    @WebEndpoint(name = "GnreConfigUF")
    public GnreConfigUFSoap getGnreConfigUF() {
        return super.getPort(GnreConfigUF, GnreConfigUFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GnreConfigUFSoap
     */
    @WebEndpoint(name = "GnreConfigUF")
    public GnreConfigUFSoap getGnreConfigUF(WebServiceFeature... features) {
        return super.getPort(GnreConfigUF, GnreConfigUFSoap.class, features);
    }

}
