package br.com.ofm.gnre.service.impl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-12-06T10:12:13.863-02:00
 * Generated source version: 2.7.18
 * 
 */
public final class GnreConfigUFSoap_GnreConfigUF_Client {

    private static final QName SERVICE_NAME = new QName("http://www.gnre.pe.gov.br/webservice/GnreConfigUF", "GnreConfigUF");

    private GnreConfigUFSoap_GnreConfigUF_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GnreConfigUF.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GnreConfigUF ss = new GnreConfigUF(wsdlURL, SERVICE_NAME);
        GnreConfigUFSoap port = ss.getGnreConfigUF();  
        
        {
        System.out.println("Invoking consultar...");
        br.com.ofm.gnre.service.impl.GnreDadosMsg _consultar_gnreDadosMsg = new br.com.ofm.gnre.service.impl.GnreDadosMsg();
        br.com.ofm.gnre.service.impl.GnreRespostaMsg _consultar__return = port.consultar(_consultar_gnreDadosMsg);
        System.out.println("consultar.result=" + _consultar__return);


        }

        System.exit(0);
    }

}
