
public class TesteString {

	public static void main(String[] args) {
		StringBuffer sql = new StringBuffer();
		sql.capacity();
		sql.append("select ps.cod_pessoa,");
		sql.append("       ps.nome,");
		sql.append("       p.cod_projeto,");
		sql.append("       p.dat_projeto,");
		sql.append("       unadm.codigo,");
		sql.append("       unadm.dsc_unadm,");
		sql.append("       sta.dsc_status_pedido,");
		sql.append("       sit.dsc_situacao_pedido,");
		sql.append("       ps_emp.COD_PESSOA       cod_empreiteira,");
		sql.append("       ps_emp.NOME             des_empreiteira,");
		sql.append("       emprei.cod_contrato_integrado,                                        ");
		sql.append("       mat_exec.cod_material,");
		sql.append("       m.descricao,");
		sql.append("       null cod_mao_obra,");
		sql.append("       null mao_obra,");
		sql.append("       ev.cod_evento,");
		sql.append("       ev.descricao_evento,");
		sql.append("      (select nvl(sum(decode(mov.ind_processo,");
		sql.append("                              0,");
		sql.append("                              decode(mov.deb_cred, 0, 1, -1) *");
		sql.append("                              mov.qtd_movimento)),");
		sql.append("                   0)");
		sql.append("          from atv_projeto_mat_exec_mov mov");
		sql.append("         where mov.id_projeto_material_exec =");
		sql.append("               mat_exec.id_projeto_material_exec) as qtd_projetado,");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      1,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) qtd_requisitado,");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      2,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) +");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      8,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) +");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      11,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) qtd_entregue,");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      3,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) qtd_camcelado,");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      4,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) qtd_complementado,");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      9,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) qtd_aplicado,");
		sql.append("       nvl(null, 0) qtd_medida,");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      5,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) +");
		sql.append("       nvl(sum(decode(mov.ind_processo,");
		sql.append("                      6,");
		sql.append("                      decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)),");
		sql.append("           0) qtd_devolucao,");
		sql.append("       (CASE");
		sql.append("         WHEN ((ev.ind_configuracao_especifica = 2) OR");
		sql.append("              (ev.ind_configuracao_especifica = 3) OR");
		sql.append("              (ev.ind_configuracao_especifica = 0)) AND");
		sql.append("              ((te.ind_requisita_material = 0) OR");
		sql.append("              (te.ind_aplicacao_direta = 0)) THEN");
		sql.append("          nvl((select sum(pm.vlr_item * pm.qtd_material)");
		sql.append("                from atv_projeto_material pm");
		sql.append("               where pm.id_projeto = p.id_projeto");
		sql.append("                 and pm.codigo_material = mat_exec.cod_material");
		sql.append("                 and pm.id_evento = mat_exec.id_evento),");
		sql.append("              0)");
		sql.append("         WHEN ((ev.ind_configuracao_especifica = 1) OR");
		sql.append("              (ev.ind_configuracao_especifica = 0)) AND");
		sql.append("              ((te.ind_devolve_material = 0)) THEN");
		sql.append("          0");
		sql.append("       END) vlr_previsto,");
		sql.append("       (CASE");
		sql.append("         WHEN ((ev.ind_configuracao_especifica = 2) OR");
		sql.append("              (ev.ind_configuracao_especifica = 3) OR");
		sql.append("              (ev.ind_configuracao_especifica = 0)) AND");
		sql.append("              ((te.ind_requisita_material = 0) OR");
		sql.append("              (te.ind_aplicacao_direta = 0)) THEN");
		sql.append("          nvl(sum(decode(mov.ind_processo,");
		sql.append("                         9,");
		sql.append("                         decode(mov.deb_cred, 0, 1, -1) * mov.vlr_item) *");
		sql.append("                  mov.qtd_movimento),");
		sql.append("              0)");
		sql.append("         WHEN ((ev.ind_configuracao_especifica = 1) OR");
		sql.append("              (ev.ind_configuracao_especifica = 0)) AND");
		sql.append("              ((te.ind_devolve_material = 0)) THEN");
		sql.append("          0");
		sql.append("       END) vlr_realizado");
		sql.append("  from atv_projeto               p,");
		sql.append("       cad_unadm                 unadm,");
		sql.append("       cad_pessoa                ps,");
		sql.append("       atv_status_pedido         sta,");
		sql.append("       atv_situacao_pedido       sit,");
		sql.append("       atv_projeto_material_exec mat_exec,");
		sql.append("       atv_projeto_mat_exec_mov  mov,");
		sql.append("       atv_evento                ev,");
		sql.append("       ATV_PROJETO_EMPREITEIRA   emprei,");
		sql.append("       cad_pessoa                ps_emp,");
		sql.append("       atv_tipo_evento           te,");
		sql.append("       tmp_material              m");
		sql.append(" where unadm.cod_unadm = p.cod_unadm_resp");
		sql.append("   and ps.cod_pessoa = p.cod_pessoa_cliente");
		sql.append("   and p.id_status_pedido = sta.id_status_pedido");
		sql.append("   and p.id_situacao_pedido = sit.id_situacao_pedido");
		sql.append("   AND p.id_projeto = mat_exec.id_projeto");
		sql.append("   and ev.id_evento = mat_exec.id_evento");
		sql.append("   and ev.id_tipo_evento = te.id_tipo_evento");
		sql.append("   and mat_exec.id_projeto_material_exec = mov.id_projeto_material_exec");
		sql.append("   and emprei.id_projeto = p.id_projeto");
		sql.append("   and ps_emp.cod_pessoa = emprei.id_empreiteira");
		sql.append("   and p.id_projeto = nvl(:p_projeto, p.id_projeto)");
		sql.append("   and p.cod_unadm_resp = nvl(:p_codigo_ua_responsavel, p.cod_unadm_resp)");
		sql.append("   and p.cod_empresa = :p_empresa");
		sql.append("   and trunc(mov.dat_movimento) <=");
		sql.append("       nvl(to_date(:data_referencia, 'DD/MM/YYYY'), mov.dat_movimento)");
		sql.append("   and mov.COD_PESSOA_EMPREITEIRA =");
		sql.append("       nvl(:p_empreiteira, mov.COD_PESSOA_EMPREITEIRA)");
		sql.append("   and (emprei.cod_contrato_integrado =");
		sql.append("       nvl(:p_contrato, mov.codigo_contrato) or");
		sql.append("       mov.codigo_contrato is null)");
		sql.append("   and emprei.cod_contrato_integrado = mov.codigo_contrato");
		sql.append("   and mat_exec.cod_material = m.codigo(+)");
		sql.append("   and (:p_tipoDataProjetoSelecionada is null or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 1 and p.dat_projeto is not null and");
		sql.append("       p.dat_projeto between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')) or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 2 and p.dat_projeto is not null and");
		sql.append("       p.dth_calculo is not null and");
		sql.append("       p.dth_calculo between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')) or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 3 and p.dat_projeto is not null and");
		sql.append("       p.dth_calculo is not null and p.dth_aeo is not null and");
		sql.append("       p.dth_aeo between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')) or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 4 and p.dat_projeto is not null and");
		sql.append("       p.dth_calculo is not null and p.dth_aeo is not null and");
		sql.append("       p.dth_fechamento is not null and");
		sql.append("       p.dth_fechamento between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')))");
		sql.append(" group by ps.cod_pessoa,");
		sql.append("          ps.nome,");
		sql.append("          p.cod_projeto,");
		sql.append("          p.dat_projeto,");
		sql.append("          unadm.codigo,");
		sql.append("          unadm.dsc_unadm,");
		sql.append("          sta.dsc_status_pedido,");
		sql.append("          sit.dsc_situacao_pedido,");
		sql.append("          ps_emp.COD_PESSOA,");
		sql.append("          ps_emp.NOME,");
		sql.append("          mat_exec.id_projeto_material_exec,");
		sql.append("          emprei.cod_contrato_integrado,");
		sql.append("          mat_exec.cod_material,");
		sql.append("          m.descricao,");
		sql.append("          ev.cod_evento,");
		sql.append("          ev.descricao_evento,");
		sql.append("          te.ind_aplicacao_direta,");
		sql.append("          ev.ind_configuracao_especifica,");
		sql.append("          te.ind_requisita_material,");
		sql.append("          te.ind_devolve_material,");
		sql.append("          p.id_projeto,");
		sql.append("          mat_exec.id_evento ");
		sql.append("having(:filtro_materiais = 0) or (:filtro_materiais = 1 and (nvl(sum(decode(mov.ind_processo, 0, decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)), 0) - nvl(sum(decode(mov.ind_processo, 1, decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)), 0) > 0)) or (:filtro_materiais = 2 and (nvl(sum(decode(mov.ind_processo, 1, decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)), 0) - nvl(sum(decode(mov.ind_processo, 2, decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)), 0) > 0)) or (:filtro_materiais = 3 and (nvl(sum(decode(mov.ind_processo, 1, decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)), 0) - nvl(sum(decode(mov.ind_processo, 2, decode(mov.deb_cred, 0, 1, -1) * mov.qtd_movimento)), 0) = 0))");
		sql.append(" UNION ");
		sql.append(" select ps.cod_pessoa,");
		sql.append("       ps.nome,");
		sql.append("       p.cod_projeto,");
		sql.append("       p.dat_projeto,");
		sql.append("       unadm.codigo,");
		sql.append("       unadm.dsc_unadm,");
		sql.append("       sta.dsc_status_pedido,");
		sql.append("       sit.dsc_situacao_pedido,");
		sql.append("       ps.COD_PESSOA cod_empreiteira,");
		sql.append("       ps.NOME des_empreiteira,");
		sql.append("       emprei.cod_contrato_integrado as cod_contrato_integrado,");
		sql.append("       null,");
		sql.append("       null,");
		sql.append("       obra.cod_mao_obra,");
		sql.append("       obra.dsc_mao_obra mao_obra,");
		sql.append("       ev.cod_evento,");
		sql.append("       ev.descricao_evento evento,");
		sql.append("       (select nvl(sum(decode(mov.ind_processo,");
		sql.append("                              0,");
		sql.append("                              decode(mov.deb_cred, 0, 1, -1) *");
		sql.append("                              mov.qtd_movimento)),");
		sql.append("                   0)");
		sql.append("          from atv_projeto_m_obr_exec_mov mov");
		sql.append("         where mov.id_projeto_mao_obra_exec =");
		sql.append("               mao_exec.id_projeto_mao_obra_exec) as qtd_projetado,");
		sql.append("       nvl(null, 0),");
		sql.append("       nvl(null, 0),");
		sql.append("       nvl(sum(decode(Mao.ind_processo,");
		sql.append("                      3,");
		sql.append("                      decode(Mao.deb_cred, 0, 1, -1) * Mao.qtd_movimento)),");
		sql.append("           0) qtd_camcelado,");
		sql.append("       nvl(sum(decode(Mao.ind_processo,");
		sql.append("                      4,");
		sql.append("                      decode(Mao.deb_cred, 0, 1, -1) * Mao.qtd_movimento)),");
		sql.append("           0) qtd_complementado,");
		sql.append("       nvl(null, 0),");
		sql.append("       nvl(sum(decode(Mao.ind_processo,");
		sql.append("                      9,");
		sql.append("                      decode(Mao.deb_cred, 0, 1, -1) * Mao.qtd_movimento)),");
		sql.append("           0) qtd_medida,");
		sql.append("       nvl(null, 0),");
		sql.append("       nvl((select sum(pmao.vlr_item * pmao.qtd_mao_obra)");
		sql.append("             from atv_projeto_mao_obra pmao");
		sql.append("            where pmao.id_projeto = p.id_projeto");
		sql.append("              and pmao.id_mao_obra = mao_exec.id_mao_obra");
		sql.append("              and pmao.id_evento = mao_exec.id_evento),");
		sql.append("           0) vlr_previsto,");
		sql.append("       nvl(sum(decode(Mao.ind_processo,");
		sql.append("                      9,");
		sql.append("                      decode(Mao.deb_cred, 0, 1, -1) *");
		sql.append("                      (select (sum(vlr_mao_obra) /");
		sql.append("                              decode(nvl(sum(bi.qtd_medida), 0),");
		sql.append("                                      0,");
		sql.append("                                      1,");
		sql.append("                                      sum(bi.qtd_medida)))");
		sql.append("                         from atv_boletim_medicao_item bi");
		sql.append("                        where bi.id_boletim_medicao in");
		sql.append("                              (select b.id_boletim_medicao");
		sql.append("                                 from atv_boletim_medicao b");
		sql.append("                                where b.id_projeto = p.id_projeto");
		sql.append("                                  and b.ind_situacao = 0)");
		sql.append("                          and bi.id_projeto_mao_obra_exec =");
		sql.append("                              mao_exec.id_projeto_mao_obra_exec)) *");
		sql.append("               Mao.qtd_movimento),");
		sql.append("           0) vlr_realizado");
		sql.append("  from atv_projeto                p,");
		sql.append("       atv_projeto_mao_obra_exec  mao_exec,");
		sql.append("       atv_projeto_m_obr_exec_mov mao,");
		sql.append("       atv_evento                 ev,");
		sql.append("       ATV_PROJETO_EMPREITEIRA    emprei,");
		sql.append("       atv_projeto_empreit_item   empitem,");
		sql.append("       atv_mao_obra               obra,");
		sql.append("       cad_pessoa                 ps,");
		sql.append("       cad_unadm                  unadm,");
		sql.append("       atv_status_pedido          sta,");
		sql.append("       atv_situacao_pedido        sit");
		sql.append(" where p.id_projeto = mao_exec.id_projeto");
		sql.append("   and ev.id_evento = mao_exec.id_evento");
		sql.append("   and obra.id_mao_obra = mao_exec.id_mao_obra");
		sql.append("   and mao_exec.id_projeto_mao_obra_exec = mao.id_projeto_mao_obra_exec");
		sql.append("   and emprei.id_projeto = mao_exec.id_projeto");
		sql.append("   and empitem.id_projeto_empreiteira = emprei.id_projeto_empreiteira");
		sql.append("   and empitem.ID_PROJETO_MAO_OBRA_EXEC = mao_exec.id_projeto_mao_obra_exec");
		sql.append("   and p.id_projeto = nvl(:p_projeto, p.id_projeto)");
		sql.append("   and p.cod_unadm_resp = nvl(:p_codigo_ua_responsavel, p.cod_unadm_resp)");
		sql.append("   and p.cod_empresa = :p_empresa");
		sql.append("   and trunc(mao.dat_movimento) <= ");
		sql.append("       nvl(to_date(:data_referencia, 'DD/MM/YYYY'), mao.dat_movimento)");
		sql.append("   and emprei.id_empreiteira = nvl(:p_empreiteira, emprei.id_empreiteira)");
		sql.append("   and emprei.cod_contrato_integrado =");
		sql.append("       nvl(to_char(:p_contrato), emprei.cod_contrato_integrado)");
		sql.append("   and (mao.codigo_contrato = nvl(:p_contrato, mao.codigo_contrato) or");
		sql.append("       mao.codigo_contrato is null)");
		sql.append("   and (mao.COD_PESSOA_EMPREITEIRA =");
		sql.append("       nvl(:p_empreiteira, mao.COD_PESSOA_EMPREITEIRA) or");
		sql.append("       mao.COD_PESSOA_EMPREITEIRA is null)");
		sql.append("   and ps.cod_pessoa = p.cod_pessoa_cliente");
		sql.append("   and unadm.cod_unadm = p.cod_unadm_resp");
		sql.append("   and p.id_status_pedido = sta.id_status_pedido");
		sql.append("   and p.id_situacao_pedido = sit.id_situacao_pedido");
		sql.append("   and mao.codigo_contrato = emprei.cod_contrato_integrado");
		sql.append("   and (:p_tipoDataProjetoSelecionada is null or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 1 and p.dat_projeto is not null and");
		sql.append("       p.dat_projeto between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')) or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 2 and p.dat_projeto is not null and");
		sql.append("       p.dth_calculo is not null and");
		sql.append("       p.dth_calculo between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')) or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 3 and p.dat_projeto is not null and");
		sql.append("       p.dth_calculo is not null and p.dth_aeo is not null and");
		sql.append("       p.dth_aeo between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')) or");
		sql.append("       (:p_tipoDataProjetoSelecionada = 4 and p.dat_projeto is not null and");
		sql.append("       p.dth_calculo is not null and p.dth_aeo is not null and");
		sql.append("       p.dth_fechamento is not null and");
		sql.append("       p.dth_fechamento between to_date(:p_data_inicial, 'dd/mm/yyyy') and");
		sql.append("       to_date(:p_data_final, 'dd/mm/yyyy')))");
		sql.append(" group by obra.cod_mao_obra,");
		sql.append("          obra.dsc_mao_obra,");
		sql.append("          ev.cod_evento,");
		sql.append("          ev.descricao_evento,");
		sql.append("          ev.id_evento,");
		sql.append("          obra.id_mao_obra,");
		sql.append("          obra.IND_CONCEBE_UC,");
		sql.append("          mao_exec.id_projeto_mao_obra_exec,");
		sql.append("          emprei.id_empreiteira,");
		sql.append("          ev.cod_evento,");
		sql.append("          obra.cod_mao_obra,");
		sql.append("          mao_exec.id_mao_obra,");
		sql.append("          mao_exec.id_evento,");
		sql.append("          p.id_projeto,");
		sql.append("          p.cod_projeto,");
		sql.append("          p.dat_projeto,");
		sql.append("          emprei.cod_contrato_integrado,");
		sql.append("          ps.cod_pessoa,");
		sql.append("          ps.nome,");
		sql.append("          unadm.codigo,");
		sql.append("          unadm.dsc_unadm,");
		sql.append("          sta.dsc_status_pedido,");
		sql.append("          sit.dsc_situacao_pedido");
		
		System.out.println(sql.toString());

	}

}
